// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/KaranJayakumar/remember/ent/connection"
	"github.com/KaranJayakumar/remember/ent/note"
	"github.com/KaranJayakumar/remember/ent/schema"
	"github.com/KaranJayakumar/remember/ent/tag"
	"github.com/KaranJayakumar/remember/ent/workspace"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	connectionFields := schema.Connection{}.Fields()
	_ = connectionFields
	// connectionDescName is the schema descriptor for name field.
	connectionDescName := connectionFields[2].Descriptor()
	// connection.NameValidator is a validator for the "name" field. It is called by the builders before save.
	connection.NameValidator = connectionDescName.Validators[0].(func(string) error)
	// connectionDescID is the schema descriptor for id field.
	connectionDescID := connectionFields[0].Descriptor()
	// connection.DefaultID holds the default value on creation for the id field.
	connection.DefaultID = connectionDescID.Default.(func() uuid.UUID)
	noteFields := schema.Note{}.Fields()
	_ = noteFields
	// noteDescContent is the schema descriptor for content field.
	noteDescContent := noteFields[1].Descriptor()
	// note.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	note.ContentValidator = noteDescContent.Validators[0].(func(string) error)
	tagFields := schema.Tag{}.Fields()
	_ = tagFields
	// tagDescName is the schema descriptor for name field.
	tagDescName := tagFields[0].Descriptor()
	// tag.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tag.NameValidator = tagDescName.Validators[0].(func(string) error)
	workspaceFields := schema.Workspace{}.Fields()
	_ = workspaceFields
	// workspaceDescName is the schema descriptor for name field.
	workspaceDescName := workspaceFields[1].Descriptor()
	// workspace.DefaultName holds the default value on creation for the name field.
	workspace.DefaultName = workspaceDescName.Default.(string)
	// workspace.NameValidator is a validator for the "name" field. It is called by the builders before save.
	workspace.NameValidator = workspaceDescName.Validators[0].(func(string) error)
	// workspaceDescID is the schema descriptor for id field.
	workspaceDescID := workspaceFields[0].Descriptor()
	// workspace.DefaultID holds the default value on creation for the id field.
	workspace.DefaultID = workspaceDescID.Default.(func() uuid.UUID)
}
