version: '3.9'

name: remember

services:
  server:
    build: ./server
    volumes:
      - ./server:/app      
    env_file:
      - ./server/.env
    depends_on:
      - aws
    ports:
      - "4444:4444"
  aws:
    image: floci/floci:latest-aws
    ports:
      - "5555:4566"
    environment:
      - SERVICES=s3
