// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Connection is the predicate function for connection builders.
type Connection func(*sql.Selector)

// Memory is the predicate function for memory builders.
type Memory func(*sql.Selector)
