// Code generated by ent, DO NOT EDIT.

package connection

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/KaranJayakumar/remember/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Connection {
	return predicate.Connection(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Connection {
	return predicate.Connection(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Connection {
	return predicate.Connection(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Connection {
	return predicate.Connection(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Connection {
	return predicate.Connection(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Connection {
	return predicate.Connection(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Connection {
	return predicate.Connection(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Connection {
	return predicate.Connection(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Connection {
	return predicate.Connection(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Connection {
	return predicate.Connection(sql.FieldEQ(FieldName, v))
}

// ParentUserId applies equality check predicate on the "parentUserId" field. It's identical to ParentUserIdEQ.
func ParentUserId(v string) predicate.Connection {
	return predicate.Connection(sql.FieldEQ(FieldParentUserId, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Connection {
	return predicate.Connection(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Connection {
	return predicate.Connection(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Connection {
	return predicate.Connection(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Connection {
	return predicate.Connection(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Connection {
	return predicate.Connection(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Connection {
	return predicate.Connection(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Connection {
	return predicate.Connection(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Connection {
	return predicate.Connection(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Connection {
	return predicate.Connection(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Connection {
	return predicate.Connection(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Connection {
	return predicate.Connection(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Connection {
	return predicate.Connection(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Connection {
	return predicate.Connection(sql.FieldContainsFold(FieldName, v))
}

// ParentUserIdEQ applies the EQ predicate on the "parentUserId" field.
func ParentUserIdEQ(v string) predicate.Connection {
	return predicate.Connection(sql.FieldEQ(FieldParentUserId, v))
}

// ParentUserIdNEQ applies the NEQ predicate on the "parentUserId" field.
func ParentUserIdNEQ(v string) predicate.Connection {
	return predicate.Connection(sql.FieldNEQ(FieldParentUserId, v))
}

// ParentUserIdIn applies the In predicate on the "parentUserId" field.
func ParentUserIdIn(vs ...string) predicate.Connection {
	return predicate.Connection(sql.FieldIn(FieldParentUserId, vs...))
}

// ParentUserIdNotIn applies the NotIn predicate on the "parentUserId" field.
func ParentUserIdNotIn(vs ...string) predicate.Connection {
	return predicate.Connection(sql.FieldNotIn(FieldParentUserId, vs...))
}

// ParentUserIdGT applies the GT predicate on the "parentUserId" field.
func ParentUserIdGT(v string) predicate.Connection {
	return predicate.Connection(sql.FieldGT(FieldParentUserId, v))
}

// ParentUserIdGTE applies the GTE predicate on the "parentUserId" field.
func ParentUserIdGTE(v string) predicate.Connection {
	return predicate.Connection(sql.FieldGTE(FieldParentUserId, v))
}

// ParentUserIdLT applies the LT predicate on the "parentUserId" field.
func ParentUserIdLT(v string) predicate.Connection {
	return predicate.Connection(sql.FieldLT(FieldParentUserId, v))
}

// ParentUserIdLTE applies the LTE predicate on the "parentUserId" field.
func ParentUserIdLTE(v string) predicate.Connection {
	return predicate.Connection(sql.FieldLTE(FieldParentUserId, v))
}

// ParentUserIdContains applies the Contains predicate on the "parentUserId" field.
func ParentUserIdContains(v string) predicate.Connection {
	return predicate.Connection(sql.FieldContains(FieldParentUserId, v))
}

// ParentUserIdHasPrefix applies the HasPrefix predicate on the "parentUserId" field.
func ParentUserIdHasPrefix(v string) predicate.Connection {
	return predicate.Connection(sql.FieldHasPrefix(FieldParentUserId, v))
}

// ParentUserIdHasSuffix applies the HasSuffix predicate on the "parentUserId" field.
func ParentUserIdHasSuffix(v string) predicate.Connection {
	return predicate.Connection(sql.FieldHasSuffix(FieldParentUserId, v))
}

// ParentUserIdEqualFold applies the EqualFold predicate on the "parentUserId" field.
func ParentUserIdEqualFold(v string) predicate.Connection {
	return predicate.Connection(sql.FieldEqualFold(FieldParentUserId, v))
}

// ParentUserIdContainsFold applies the ContainsFold predicate on the "parentUserId" field.
func ParentUserIdContainsFold(v string) predicate.Connection {
	return predicate.Connection(sql.FieldContainsFold(FieldParentUserId, v))
}

// HasMemories applies the HasEdge predicate on the "memories" edge.
func HasMemories() predicate.Connection {
	return predicate.Connection(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MemoriesTable, MemoriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMemoriesWith applies the HasEdge predicate on the "memories" edge with a given conditions (other predicates).
func HasMemoriesWith(preds ...predicate.Memory) predicate.Connection {
	return predicate.Connection(func(s *sql.Selector) {
		step := newMemoriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Connection) predicate.Connection {
	return predicate.Connection(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Connection) predicate.Connection {
	return predicate.Connection(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Connection) predicate.Connection {
	return predicate.Connection(sql.NotPredicates(p))
}
