// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MemoriesColumns holds the columns for the "Memories" table.
	MemoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "person_memories", Type: field.TypeInt},
	}
	// MemoriesTable holds the schema information for the "Memories" table.
	MemoriesTable = &schema.Table{
		Name:       "Memories",
		Columns:    MemoriesColumns,
		PrimaryKey: []*schema.Column{MemoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "Memories_People_memories",
				Columns:    []*schema.Column{MemoriesColumns[2]},
				RefColumns: []*schema.Column{PeopleColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PeopleColumns holds the columns for the "People" table.
	PeopleColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// PeopleTable holds the schema information for the "People" table.
	PeopleTable = &schema.Table{
		Name:       "People",
		Columns:    PeopleColumns,
		PrimaryKey: []*schema.Column{PeopleColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MemoriesTable,
		PeopleTable,
	}
)

func init() {
	MemoriesTable.ForeignKeys[0].RefTable = PeopleTable
	MemoriesTable.Annotation = &entsql.Annotation{
		Table: "Memories",
	}
	PeopleTable.Annotation = &entsql.Annotation{
		Table: "People",
	}
}
